const $=selector=>document.querySelector(selector);
const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name,cls='')=>`<svg class="${cls}" aria-hidden="true"><use href="#${e(name)}"/></svg>`;
const logo=platform=>icon(`logo-${platform}`);
const day=value=>value&&Number.isFinite(Date.parse(value))?new Date(value).toISOString().slice(0,10):'?';
const host=url=>{try{return new URL(url).hostname;}catch{return '';}};
const platform=url=>{const h=host(url);return /(^|\.)youtube\.com$|youtu\.be$/.test(h)?'youtube':/instagram\.com$/.test(h)?'instagram':/^(www\.)?(x|twitter)\.com$/.test(h)?'x':h==='github.com'?'github':h==='news.ycombinator.com'?'hackernews':h.includes('anthropic.com')||h==='platform.claude.com'?'anthropic':h==='arxiv.org'?'arxiv':h.includes('modelcontextprotocol.io')?'mcp':'web';};
let graph=null,active=false,focus=null,selected=null,showInferred=false,researchRuns=[],activeRunId=null,lastSnapshot='',polling=false,closed=false,guide=null,contentPlatform='all',selectedContent=null;

let authenticated=false,authChecking=false,authGeneration=0,authUserId=null;
const STALE_RESPONSE='Account changed; ignored stale response.';
async function api(path,options={}){const generation=authGeneration;const response=await fetch(path,{...options,headers:{'content-type':'application/json',...options.headers}});let data;try{data=await response.json();}catch{throw new Error('Could not read the server response.');}if(generation!==authGeneration)throw new Error(STALE_RESPONSE);if(response.status===401){showLogin({status:'signed-out'});throw new Error('Sign in with Agentlas to continue.');}if(!response.ok)throw new Error(typeof data.error==='string'?data.error:`HTTP ${response.status}`);return data;}
function status(message,ok=false){if(message===STALE_RESPONSE)return;$('#graph-status').textContent=message;$('#graph-status').classList.toggle('ok',ok);}
function metric(doc){
  const m=doc?.metrics;
  if(!m||m.status!=='observed'){const reported=m?.status==='agent-reported'?`AI report: ${['views','likes','comments','points','stars'].filter(k=>m[k]!=null).map(k=>`${k} ${m[k]}`).join(', ')||'no metrics'}. Not app verified.`:m?.status==='discovered'?'Search candidate; original-page metrics unknown.':'Views and engagement unknown; missing does not mean zero.';return {unit:'unknown',value:null,label:'?',title:reported};}
  if(m.platform==='hackernews'&&m.points!==null)return {unit:'points',value:m.points,label:`↑ ${m.points}`,title:`Public HN points ${m.points} · comments ${m.comments??'?'} · observed ${day(doc.observedAt)}. Points are not views.`};
  if(m.views!==null)return {unit:m.platform==='x'?'impressions':'views',value:m.views,label:`${m.platform==='x'?'◉':'▶'} ${m.views.toLocaleString()}`,title:`${m.platform==='x'?'Public post impressions':'Public video views'} · ${m.basis} · observed ${day(doc.observedAt)}`};
  if(m.likes!==null)return {unit:'likes',value:m.likes,label:`♡ ${m.likes.toLocaleString()}`,title:`Public likes · ${m.basis} · observed ${day(doc.observedAt)}`};
  return {unit:'unknown',value:null,label:'?',title:'Views and engagement unknown.'};
}
function currentFocus(){return graph?.rankings.find(s=>s.id===focus);}
function strategies(){return graph?.strategies??[];}
function currentRun(){return researchRuns.find(r=>r.id===activeRunId);}
const runLabels={ready:'Ready for your AI',searching:'Searching',complete:'Complete',partial:'Partial',error:'Error',cancelled:'Cancelled'};
function render(){
  if(!graph)return;
  const run=currentRun(),mode=$('#mode-indicator');mode.textContent=active?'●':'○';mode.title=active?'Public evidence in this research sample':'Waiting for public evidence';
  $('#strategy-logos').innerHTML=active?strategies().map((s,i)=>`<button class="strategy-target target-${s.rank??i+1} ${s.status==='format-hypothesis'?'hypothesis':''}" data-strategy="${e(s.id)}" aria-label="Source opportunity ${i+1}: ${e(s.action)}">${logo(s.platform)}<span class="rank-badge">${i+1}</span></button>`).join(''):'';
  $('#draft-download').href='/api/drafts';
  const c=graph.coverage;$('#scope-counters').innerHTML=active?[[c.observedCreators,'icon-people','Unique observed creators in this sample'],[c.sources,'icon-link','Discovered source URLs'],[c.unfetchedSources,'icon-info','Source pages not yet collected']].map(([n,i,t])=>`<span class="scope-counter" title="${e(t)}">${icon(i)}${n}</span>`).join(''):'';
  $('#research-session').hidden=!run;
  if(run){$('#run-status').textContent=runLabels[run.status]??run.status;$('#run-status').title=run.note??'';$('#run-url').textContent=run.url;$('#run-url').title=run.url;const p=run.progress??{};$('#run-progress').textContent=`${p.searched??0} searched · ${p.partial??0} partial${p.unavailable?` · ${p.unavailable} unavailable`:''} · ${p.records??0} records`;$('#stop-run-button').hidden=!['ready','searching'].includes(run.status);}
  const empty=$('#empty-state');empty.hidden=active;empty.querySelector('h1').textContent=run?'Your research is ready to continue.':'Find the sources behind the conversation.';empty.querySelector('p').textContent=run?(['ready','searching'].includes(run.status)?'Paste the AI task into your subscribed local AI host.':'No public findings in this run. Prepare another URL to continue.'):'Research public content with the AI you already use.';$('#empty-connect-button').textContent=run&&['ready','searching'].includes(run.status)?'Copy AI task':'Connect your AI';
  renderCarousel();drawGraph();
}
function contentNodes(){const nodes=graph?.nodes.filter(n=>n.type==='content')??[];return graph?.analysis?.mode==='audience'?nodes.filter(n=>[...(graph.analysis.contentUrls??[]),...(graph.analysis.reportedUrls??[])].includes(n.url)):nodes;}
function sortedContents(){return contentNodes().filter(n=>contentPlatform==='all'||platform(n.url)===contentPlatform).sort((a,b)=>{const pa=platform(a.url),pb=platform(b.url);if(pa!==pb)return ['youtube','instagram','x','hackernews','web','github','anthropic','arxiv','mcp'].indexOf(pa)-['youtube','instagram','x','hackernews','web','github','anthropic','arxiv','mcp'].indexOf(pb);const measured=Number(b.document.metrics?.status==='observed')-Number(a.document.metrics?.status==='observed');const ma=metric(a.document),mb=metric(b.document);const units=['views','impressions','points','likes','unknown'];return measured||(ma.unit!==mb.unit?units.indexOf(ma.unit)-units.indexOf(mb.unit):0)||(mb.value??-1)-(ma.value??-1)||a.url.localeCompare(b.url);});}
function searchLink(p){const run=currentRun(),q=run?.tasks?.find(t=>t.platform===p)?.query??graph?.analysis?.title??'';return p==='youtube'?`https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`:p==='instagram'?`https://www.instagram.com/explore/search/keyword/?q=${encodeURIComponent(q)}`:p==='x'?`https://x.com/search?q=${encodeURIComponent(q)}&f=top`:'https://news.ycombinator.com/';}
function missingPlatform(p){const state=graph?.analysis?.platformCoverage?.[p]??'ready';return `<div class="platform-empty" data-empty-platform="${e(p)}" tabindex="0" aria-label="${e(p)} · ${e(state)} · No retained content yet.">${logo(p)}<span class="availability-dot ${state==='error'?'error':''}"></span><button class="icon-button" data-connect="${e(p)}" aria-label="Connect your AI for ${e(p)}" title="Use your AI host">${icon('icon-link')}</button><a class="icon-button" href="${e(searchLink(p))}" target="_blank" rel="noopener noreferrer" aria-label="Open public ${e(p)} search" title="Open platform search">${icon('icon-arrow')}</a></div>`;}
function renderCarousel(){
  const contents=active?sortedContents():[];
  if(!contents.some(n=>n.id===selectedContent))selectedContent=contents[0]?.id??null;
  const labels=graph?.analysis?.labels??[];
  $('#topic-chips').innerHTML=active?labels.map(t=>`<span class="topic-chip" title="${e(graph.analysis.queryBasis)}">${e(t)}</span>`).join(''):'';
  for(const b of document.querySelectorAll('[data-platform]')){b.classList.toggle('active',b.dataset.platform===contentPlatform);const state=graph.analysis?.platformCoverage?.[b.dataset.platform];b.classList.toggle('needs-connection',state==='needs-connection'||state==='error'||state==='unavailable');if(state)b.title=`${b.dataset.platform} · ${state} · Metrics stay specific to each platform`;}
  const cards=contents.map((c,i)=>{
    const p=platform(c.url),m=metric(c.document),targets=graph.edges.filter(ed=>ed.from===c.id&&ed.type==='explicit').map(ed=>graph.nodes.find(n=>n.id===ed.to)).filter(Boolean);
    const target=graph.strategies.find(t=>targets.some(n=>n.id===t.sourceId))??graph.strategies.find(t=>t.sourceId===`channel-${p}`);
    return {p,html:`<div class="carousel-item" role="listitem"><button class="content-card ${selectedContent===c.id?'selected':''} ${c.document.synthetic?'synthetic':''} ${['manual','public-index','agent-search'].includes(c.document.collection.method)?'reported':''} target-${target?.rank??0}" data-content="${e(c.id)}" aria-label="${e(c.document.synthetic?'Synthetic · excluded from rankings · ':c.document.collection.method==='agent-browser'?'AI-observed page · ':c.document.collection.method==='manual'?'Reported · not verified · ':['public-index','agent-search'].includes(c.document.collection.method)?'Search candidate · original page and metrics unknown · ':'')}${e(c.title)} · ${e(m.title)}" ><div class="content-art art-${p}" aria-hidden="true"><div class="card-orbit orbit-one"></div><div class="card-orbit orbit-two"></div>${logo(p)}<span class="content-index">${String(i+1).padStart(2,'0')}</span><span class="content-source-dots">${targets.slice(0,3).map(n=>`<span data-hover-node="${e(n.id)}">${logo(platform(n.url))}</span>`).join('')}</span></div><div class="card-caption"><span class="card-title">${e(c.title)}</span><div class="card-meta"><span>${e(c.document.creator?.name??'?')}</span><span title="${e(m.title)}">${e(m.label)}</span></div></div></button></div>`};
  });
  $('#content-carousel').innerHTML=active?(contentPlatform==='all'?['youtube','instagram','x','hackernews','web','github','anthropic','arxiv','mcp'].map(p=>cards.some(c=>c.p===p)?cards.filter(c=>c.p===p).map(c=>c.html).join(''):['youtube','instagram','x'].includes(p)?missingPlatform(p):'').join(''):cards.length?cards.map(c=>c.html).join(''):missingPlatform(contentPlatform)):`<div class="carousel-empty" aria-label="Waiting for a product URL">${logo('web')}<span>?</span></div>`;
}
function drawGraph(){
  const svg=$('#source-graph');
  let inner=`<defs><marker id="graph-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="4" markerHeight="4" orient="auto"><path d="M0 0L10 5L0 10" fill="#a2adbd"/></marker>${graph?.strategies.map(t=>`<marker id="target-arrow-${t.rank}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="4" markerHeight="4" orient="auto"><path d="M0 0L10 5L0 10" fill="${e(t.color)}"/></marker>`).join('')??''}</defs>`;
  if(!active){inner+=`<circle class="empty-core" cx="500" cy="340" r="90"/><svg x="475" y="315" width="50" height="50" opacity=".22"><use href="#icon-link"/></svg>`;svg.innerHTML=inner;return;}
  const positions=new Map(),source=currentFocus(),contents=sortedContents(),selectedPost=graph.nodes.find(n=>n.id===selectedContent);
  const postTargets=selectedPost?graph.edges.filter(ed=>ed.from===selectedPost.id&&ed.type==='explicit').map(ed=>ed.to):[];
  if(source){
    positions.set(source.id,{x:435,y:355,r:51});
    const outgoing=[...new Set(graph.edges.filter(ed=>ed.from===source.id&&(ed.type==='explicit'||showInferred&&ed.type==='inferred')).map(ed=>ed.to))].slice(0,10);
    outgoing.forEach((id,i)=>positions.set(id,{x:760+(i%2)*145,y:105+Math.floor(i/2)*115,r:28}));
    const incoming=graph.edges.filter(ed=>ed.to===source.id&&ed.type==='explicit'&&ed.from.startsWith('source-')).slice(0,3);
    incoming.forEach((ed,i)=>positions.set(ed.from,{x:270,y:190+i*135,r:25}));
    const related=graph.nodes.filter(n=>n.type==='content'&&graph.edges.some(ed=>ed.from===n.id&&ed.type==='explicit'&&(ed.to===source.id||incoming.some(x=>x.from===ed.to))));
    related.slice(0,16).forEach((c,i)=>positions.set(c.id,{x:83,y:75+i*39,r:17}));
  }else{
    const roots=[...new Set([...graph.strategies.map(t=>t.sourceId),...postTargets,...contents.flatMap(c=>graph.edges.filter(ed=>ed.from===c.id&&ed.type==='explicit').map(ed=>ed.to))])].filter(id=>graph.nodes.some(n=>n.id===id));
    const channelRoots=roots.filter(id=>id.startsWith('channel-')),sourceRoots=roots.filter(id=>!id.startsWith('channel-'));
    sourceRoots.slice(0,12).forEach((id,i)=>positions.set(id,{x:365+(i%2)*180,y:80+Math.floor(i/2)*110,r:31}));
    channelRoots.forEach((id,i)=>positions.set(id,{x:830,y:115+i*150,r:38}));
    const upstream=[...new Set(graph.edges.filter(ed=>ed.type==='explicit'&&sourceRoots.slice(0,12).includes(ed.from)).map(ed=>ed.to))].filter(id=>!positions.has(id)).slice(0,8);
    upstream.forEach((id,i)=>positions.set(id,{x:785+(i%2)*145,y:265+Math.floor(i/2)*110,r:26}));
    contents.slice(0,16).forEach((c,i)=>positions.set(c.id,{x:85,y:75+i*39,r:17}));
    if(sourceRoots.length>12)inner+=`<text class="lane-label" x="580" y="700"><title>More sources are available in rankings and JSON export</title>+${sourceRoots.length-12}</text>`;
  }
  for(const ed of graph.edges.filter(ed=>positions.has(ed.from)&&positions.has(ed.to)&&ed.type!=='publishes'&&(ed.type!=='inferred'||showInferred))){
    const a=positions.get(ed.from),b=positions.get(ed.to),forward=b.x>=a.x,sx=a.x+(forward?a.r:-a.r),tx=b.x+(forward?-b.r:b.r),bend=Math.abs(tx-sx)*.48;
    const target=graph.strategies.find(t=>t.sourceId===ed.to||t.sourceId===ed.from),onSelected=!selectedContent||ed.from===selectedContent||postTargets.includes(ed.from)||postTargets.includes(ed.to);
    const kind=ed.type==='published-on'?'hosted':ed.type==='inferred'?'inferred':ed.evidence?.status==='synthetic'?'synthetic':['reported','discovered'].includes(ed.evidence?.status)?'reported':ed.from.startsWith('source-')?'upstream':'explicit';
    inner+=`<path class="graph-edge ${kind} ${target?`target-${target.rank}`:''} ${onSelected?'selected-path':'muted-path'}" d="M ${sx} ${a.y} C ${sx+(forward?bend:-bend)} ${a.y}, ${tx-(forward?bend:-bend)} ${b.y}, ${tx} ${b.y}" marker-end="url(#${target?`target-arrow-${target.rank}`:'graph-arrow'})"><title>${e(ed.type==='published-on'?ed.evidence.basis:ed.type==='inferred'?`Inferred · excluded from scores · ${ed.rationale}`:`Public href: ${ed.evidence?.url} → ${ed.evidence?.targetUrl} · ${ed.evidence?.status}`)}</title></path>`;
  }
  for(const [id,pos] of positions){
    const n=graph.nodes.find(n=>n.id===id);if(!n)continue;const target=graph.strategies.find(t=>t.sourceId===id),s=graph.rankings.find(n=>n.id===id),content=n.type==='content',channel=n.type==='channel';
    const provenance=n.synthetic||n.document?.synthetic?'Synthetic · excluded from scores · ':n.document?.collection.method==='agent-browser'?'AI-observed page · ':n.document?.collection.method==='manual'?'Reported · excluded from scores · ':['public-index','agent-search'].includes(n.document?.collection.method)?'Search candidate · original page unknown · excluded from scores · ':'';
    const label=content?`${n.title}; ${metric(n.document).title}`:channel?`${n.title}; Public posts ${n.contentIds.length}; platform membership only`:`${n.title}; Sample score ${s?.score??0}; direct ${s?.directCreatorCount??0}, additional second-hop ${s?.secondHopCreatorCount??0}; ${n.fetched?'Page collected':'Source page not collected'}`;
    if(content){const creator=graph.nodes.find(c=>c.id===n.creatorId);if(creator)inner+=`<g data-node="${e(creator.id)}" tabindex="0" role="button" aria-label="Creator ${e(creator.name)}"><line class="author-edge" x1="${pos.x-30}" y1="${pos.y}" x2="${pos.x-pos.r}" y2="${pos.y}"/><circle class="author-disc" cx="${pos.x-31}" cy="${pos.y}" r="8"/><text class="author-initial" x="${pos.x-31}" y="${pos.y+3}">${e(creator.name.slice(0,1))}</text></g>`;}
    inner+=`<g class="graph-node ${content?'content':channel?'channel':'source'} ${postTargets.includes(id)?'related-source':''} ${target?`target-node target-${target.rank}`:''} ${!content&&!channel&&!n.fetched?'unfetched':''} ${n.synthetic||n.document?.synthetic?'synthetic':''} ${n.document?.collection.method==='manual'?'reported':''} ${selected===id||selectedContent===id?'selected':''}" data-node="${e(id)}" tabindex="0" role="button" aria-label="${e(provenance+label)}"><circle class="node-disc" cx="${pos.x}" cy="${pos.y}" r="${pos.r}"/><svg x="${pos.x-pos.r*.48}" y="${pos.y-pos.r*.48}" width="${pos.r*.96}" height="${pos.r*.96}"><use href="#logo-${platform(n.url)}"/></svg>${target?`<circle class="target-badge" cx="${pos.x+pos.r*.75}" cy="${pos.y-pos.r*.75}" r="9"/><text class="target-badge-text" x="${pos.x+pos.r*.75}" y="${pos.y-pos.r*.75+3}">${target.rank}</text>`:!content&&!channel&&!n.fetched?`<text class="node-badge-text" x="${pos.x+pos.r}" y="${pos.y-pos.r}">?</text>`:''}${!content?`<text class="node-score" x="${pos.x}" y="${pos.y+pos.r+18}">${channel?n.creatorCount:s?.eligible?s.score.toFixed(1):'?'}</text>`:''}</g>`;
  }
  svg.setAttribute('aria-label',`Public content source graph · opportunity ${graph.strategies.length} · visible ${positions.size} nodes · bounded sample`);svg.innerHTML=inner;
}
function openInspector(html){$('#inspector-body').innerHTML=html;$('#inspector').showModal();}
function dateRow(published,observed){return `<div class="evidence-date"><span title="Publication or repository creation date; not the date the link was added">◷ ${day(published)}</span><span title="Public page observation date">◉ ${day(observed)}</span></div>`;}
async function inspectNode(id){const generation=authGeneration;const n=graph?.nodes.find(n=>n.id===id);if(!n)return;selected=id;drawGraph();if(n.type==='channel'){const strategy=graph.strategies.find(t=>t.sourceId===id);if(strategy)inspectStrategy(strategy.id);return;}
  if(n.type==='creator'){openInspector(`${logo('web')}<div class="inspect-title">${e(n.name)}</div>${n.url?`<a class="inspect-url" href="${e(n.url)}" target="_blank" rel="noopener noreferrer">${e(host(n.url))} ↗</a>`:''}<div class="evidence-dots">${n.contentIds.map(cid=>{const c=graph.nodes.find(x=>x.id===cid);return `<button class="evidence-dot" data-inspect="${e(cid)}" title="${e(c.title)}">${logo(platform(c.url))}</button>`;}).join('')}</div>`);return;}
  if(n.type==='content'){const m=metric(n.document);openInspector(`${logo(platform(n.url))}<div class="inspect-title">${e(n.title)}</div><a class="inspect-url" href="${e(n.url)}" target="_blank" rel="noopener noreferrer">${e(host(n.url))} ↗</a><div class="inspect-metrics"><span title="${e(m.title)}">${e(m.label)}</span><span title="Public comment count">☷ ${n.document.metrics?.status==='observed'?n.document.metrics.comments??'?':'?'}</span><span title="${e(n.document.collection.method)} / ${e(n.document.synthetic?'synthetic':n.document.collection.trust??(n.document.collection.method==='manual'?'reported':'app-collected'))}">${n.document.synthetic?'◇':n.document.collection.method==='manual'?'◌':'●'}</span></div>${dateRow(n.document.publishedAt,n.document.observedAt)}<div class="evidence-dots">${graph.edges.filter(ed=>ed.from===id&&ed.type==='explicit').map(ed=>{const target=graph.nodes.find(x=>x.id===ed.to);return `<button class="evidence-dot" data-focus="${e(ed.to)}" title="${e(target?.title)} · Explore path">${logo(platform(target?.url))}</button>`;}).join('')}</div>`);return;}
  try{const d=await api(`/api/source?id=${encodeURIComponent(id)}`);if(!authenticated||generation!==authGeneration)return;const s=d.source;openInspector(`${logo(platform(s.url))}<div class="inspect-title">${e(s.title)}</div><a class="inspect-url" href="${e(s.url)}" target="_blank" rel="noopener noreferrer">${e(s.url)} ↗</a><div class="inspect-metrics"><span title="Sample score; not a prediction of reach or conversion">${s.score.toFixed(1)}</span><span title="Unique direct creators">${icon('icon-people')} ${s.directCreatorCount}</span><span title="Unique additional second-hop creators">${icon('icon-link')} ${s.secondHopCreatorCount}</span><span title="${s.fetched?'Source page collected':'Source page and mentions unknown'}">${s.fetched?'●':'?'}</span></div>${dateRow(s.document?.publishedAt,s.document?.observedAt)}<div class="evidence-dots">${d.incoming.slice(0,8).map(ed=>`<a class="evidence-dot" href="${e(ed.evidence.url)}" target="_blank" rel="noopener noreferrer" title="${e(ed.origin?.title)} · Published ${day(ed.evidence.publishedAt)} · Observed ${day(ed.evidence.observedAt)} · ${e(ed.evidence.status)}">${logo(platform(ed.evidence.url))}</a>`).join('')}</div><div class="dialog-actions"><button class="icon-button" data-focus="${e(id)}" title="Follow this source to its references" aria-label="Follow references">${icon('icon-arrow')}</button><button class="icon-button" data-prepare="${e(s.url)}" title="Prepare research for this URL" aria-label="Prepare research for this URL">${icon('icon-refresh')}</button></div>`);}catch(err){if(authenticated&&generation===authGeneration)status(err.message);}
}
function inspectStrategy(id){const s=strategies().find(x=>x.id===id);if(!s)return;selected=s.sourceId;drawGraph();openInspector(`${logo(s.platform)}<div class="inspect-action">${e(s.action)}</div><a class="inspect-url" href="${e(s.url)}" target="_blank" rel="noopener noreferrer" title="${e(s.caveat)}">${e(s.url)} ↗</a><div class="inspect-metrics"><span title="Local draft">◌</span><span title="Supporting paths or posts ${s.evidenceIds.length}">${icon('icon-link')} ${s.evidenceIds.length}</span></div><div class="dialog-actions">${s.sourceId?`<button class="icon-button" data-focus="${e(s.sourceId)}" title="Supporting source paths" aria-label="Supporting source paths">${icon('icon-arrow')}</button>`:''}<a class="icon-button" href="/api/drafts" download="placement-drafts.md" title="Download opportunity drafts" aria-label="Download opportunity drafts">${icon('icon-download')}</a></div>`);}
function coverage(){if(!graph)return;const c=graph.coverage;openInspector(`<div class="mini-stats">${[[c.observedCreators,'icon-people','Observed creators in this sample'],[c.observedDocuments,'icon-grid','Observed pages'],[c.unfetchedSources,'icon-info','Source page not collected'],[c.omittedLinks,'icon-link','Links omitted by selection or limits'],[c.missingDates,'icon-info','Publication date unknown'],[c.failedAttempts,'icon-close','Collection failures']].map(([n,i,t])=>`<span class="mini-stat" title="${e(t)}">${icon(i)}${n}</span>`).join('')}</div><div class="coverage-attempts">${c.attempts.slice(-30).map(a=>`<span class="attempt-dot ${a.status==='error'?'error':''}" title="${e(a.url)} · ${e(a.message)} · ${day(a.observedAt)}"></span>`).join('')}</div><div class="inspect-metrics"><span title="Observed hrefs show public connections, not influence or information acquisition.">● →</span><span title="Inferences, manual reports, and synthetic records are excluded from scores.">⋯</span><span title="Private conversations, private research, and restricted pages are outside this sample.">?</span></div><div class="evidence-date"><span title="${e(c.limitations[0])}">◌ ${c.observedContent}</span><span title="45 direct/N + 25 additional second-hop/N + 20 topics/4 + 10 evidence quality. Repeat posts do not increase unique creator counts.">ƒ</span></div>`);}
function ranks(){if(!graph)return;openInspector(`<div class="rank-icons">${graph.rankings.slice(0,18).map(s=>`<button class="rank-source" data-focus="${e(s.id)}" title="${e(s.title)} · direct ${s.directCreatorCount} · additional second-hop ${s.secondHopCreatorCount} · score ${s.score} / 100 · ${s.eligible?'Observed path':'Insufficient evidence'}" aria-label="Source ranking: ${e(s.title)}">${logo(platform(s.url))}<small>${s.score.toFixed(1)}</small></button>`).join('')}</div>`);}
function mentions(){if(!graph)return;openInspector(`<div class="brand-mentions">${graph.mentions.map(m=>`<div class="brand-mention" title="${e(m.brand)}: Literal name matches in this public sample: external content ${m.externalContentDocuments??m.observedDocuments} · input product ${m.inputProductDocuments??0}. Name matches do not establish recommendation, use, or market share."><span>${e(m.brand)}</span><b>${m.externalContentDocuments??m.observedDocuments}</b></div>`).join('')}</div>`);}
async function connections(){
  const generation=authGeneration;try{const response=guide??await api('/api/agent/guide');if(!authenticated||generation!==authGeneration)return;guide=response;openInspector(`<div class="setup-guide"><h2>Connect your AI</h2><p>Use your existing Claude Code or Codex plan.</p><ol><li>Install the research skill.<p class="guide-detail">Downloaded app: run <code>${e(guide.packagedInstall)}</code></p><p class="guide-detail">From source:</p><div class="command-row"><code>${e(guide.install)}</code><button class="icon-button" data-copy="${e(guide.install)}" title="Copy installation command" aria-label="Copy installation command">${icon('icon-link')}</button></div></li><li>Enter a product URL here, then copy the AI task.</li><li>Run it in your AI host.${guide.hosts.map(h=>`<div class="host-command"><strong>${e(h.name)}</strong><code>${e(h.command)} URL</code></div>`).join('')}</li></ol><p class="guide-detail">${e(guide.requirement)}</p><p class="guide-detail">Search and browsing run through your AI host. No provider API keys or separate LLM billing.</p><div class="dialog-actions"><button class="text-button" data-close>Done</button></div><div id="copy-status" role="status" aria-live="polite"></div></div>`);}catch(err){if(authenticated&&generation===authGeneration)status(err.message);}
}
function aiTask(){const run=currentRun();if(!run)throw new Error('Prepare a product URL first.');return `Research ${run.url} using your creator-source-graph skill. Use existing research run ${run.id}; do not create a new run.\nClaude Code: /creator-source-graph ${run.url} --run ${run.id}\nCodex: $creator-source-graph ${run.url} --run ${run.id}\nRun your host's web search and browser tools, open original public pages, follow actual hrefs, and submit bounded public metadata and truthful coverage to this run. Respect login and access restrictions.`;}
async function copyText(value){const generation=authGeneration;try{await navigator.clipboard.writeText(value);if(!authenticated||generation!==authGeneration)return;const target=$('#copy-status');if(target)target.textContent='Copied.';else status('AI task copied.',true);}catch{if(!authenticated||generation!==authGeneration)return;openInspector(`<h2>Copy this text</h2><textarea class="copy-fallback" readonly aria-label="Text to copy">${e(value)}</textarea><p class="guide-detail">Select the text and copy it to your AI host.</p>`);const field=$('.copy-fallback');field.focus();field.select();}}
async function copyTask(){try{await copyText(aiTask());}catch(err){status(err.message);}}
function history(){openInspector(`<h2>Research history</h2><div class="run-history">${researchRuns.length?[...researchRuns].reverse().map(r=>`<article><strong>${e(runLabels[r.status]??r.status)}</strong><time>${day(r.createdAt)}</time><p class="history-url">${e(r.url)}</p><p>${e(r.note??'')}</p></article>`).join(''):'<p>No research runs yet.</p>'}</div>`);}
function acceptWorkspace(data,{reset=false}={}){
  if(!authenticated)return;
  const snapshot=JSON.stringify(data);if(!reset&&snapshot===lastSnapshot)return;lastSnapshot=snapshot;graph=data;researchRuns=data.researchRuns??researchRuns;activeRunId=Object.hasOwn(data,'activeResearchRunId')?data.activeResearchRunId:activeRunId;active=(graph.coverage?.documents??0)>0;
  if(reset){focus=null;selected=null;selectedContent=null;contentPlatform='all';}
  if(focus&&!graph.nodes.some(n=>n.id===focus))focus=null;if(selected&&!graph.nodes.some(n=>n.id===selected))selected=null;
  if(!$('#input-url').value&&graph.analysis?.url)$('#input-url').value=graph.analysis.url;
  const rail=$('#content-carousel'),scroll=rail.scrollTop;render();rail.scrollTop=scroll;
}
async function refresh({quiet=false}={}){if(polling||closed||!authenticated)return;const generation=authGeneration;polling=true;try{const data=await api('/api/workspace');if(!authenticated||generation!==authGeneration)return;acceptWorkspace(data);if(!quiet)status('');}catch(err){if(!quiet&&authenticated&&generation===authGeneration)status(err.message);}finally{polling=false;}}
const hoverSelector='[data-hover-node],[data-node],[data-content],[data-strategy],[data-platform],[data-empty-platform],[data-inspect],[data-focus]';
let hoverTimer=null,hoverCloseTimer=null,hoverAnchor=null;
const platformNames={all:'All platforms',youtube:'YouTube',instagram:'Instagram',x:'X',hackernews:'Hacker News',web:'Public web',github:'GitHub',anthropic:'Anthropic',arxiv:'arXiv',mcp:'Model Context Protocol'};
const platformUrls={youtube:'https://www.youtube.com/',instagram:'https://www.instagram.com/',x:'https://x.com/',hackernews:'https://news.ycombinator.com/',web:'https://agentlas.cloud',github:'https://github.com/',anthropic:'https://www.anthropic.com/',arxiv:'https://arxiv.org/',mcp:'https://modelcontextprotocol.io/'};
function publicHref(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function previewData(anchor){
  const id=anchor.dataset.hoverNode??anchor.dataset.node??anchor.dataset.content??anchor.dataset.inspect??anchor.dataset.focus;
  const n=graph?.nodes.find(n=>n.id===id),s=anchor.dataset.strategy?strategies().find(s=>s.id===anchor.dataset.strategy):null;
  if(n||s){const doc=n?.document??graph?.nodes.find(n=>n.id===s?.sourceId)?.document;const incoming=graph?.edges.filter(ed=>ed.to===(n?.id??s?.sourceId)&&ed.type==='explicit')??[];
    const aiSummary=typeof doc?.summary==='string'&&doc.summary.trim()?doc.summary.trim():null;
    const summary=aiSummary||doc?.collection?.note||doc?.topics?.join(' · ')||(n?.type==='creator'?`${n.contentIds?.length??0} public content records in this sample.`:n?.type==='channel'?`${n.contentIds?.length??0} retained public posts. Platform membership only.`:s?`${s.action}. ${s.evidenceIds?.length??0} supporting paths in this sample.`:incoming.length?`${incoming.length} retained public links point to this source. Page summary unavailable.`:'Page summary unavailable. Inspect the original source.');
    return {title:n?.title??n?.name??s?.action??'Public source',url:n?.url??s?.url,summary:String(summary).slice(0,300),aiSummary:!!aiSummary,date:day(doc?.observedAt??incoming[0]?.evidence?.observedAt),state:doc?.collection?.trust??doc?.collection?.method??(n?.type==='creator'?'Creator metadata':n?.type==='channel'?'Platform metadata':'Source page not collected')};
  }
  const p=anchor.dataset.platform??anchor.dataset.emptyPlatform;if(p){const task=currentRun()?.tasks?.find(t=>t.platform===p),count=contentNodes().filter(n=>p==='all'||platform(n.url)===p).length;return {title:platformNames[p]??p,url:p==='all'?null:platformUrls[p],summary:task?.note||`${count} retained content records. Platform filtering does not establish reach or views.`,date:day(currentRun()?.updatedAt),state:task?.status??graph?.analysis?.platformCoverage?.[p]??'Coverage unknown'};}
  return null;
}
function hideHover(){clearTimeout(hoverTimer);clearTimeout(hoverCloseTimer);$('#hover-card').hidden=true;hoverAnchor=null;}
function placeHover(){const card=$('#hover-card');if(card.hidden||!hoverAnchor?.isConnected){hideHover();return;}const a=hoverAnchor.getBoundingClientRect(),r=card.getBoundingClientRect(),pad=12;let left=Math.min(Math.max(pad,a.left+a.width/2-r.width/2),Math.max(pad,innerWidth-r.width-pad)),top=a.bottom+9;if(top+r.height>innerHeight-pad)top=Math.max(pad,a.top-r.height-9);card.style.left=`${left}px`;card.style.top=`${Math.min(top,Math.max(pad,innerHeight-r.height-pad))}px`;}
function showHover(anchor){if(!authenticated)return;const data=previewData(anchor);if(!data)return;clearTimeout(hoverCloseTimer);hoverAnchor=anchor;const url=publicHref(data.url),card=$('#hover-card');card.innerHTML=`<strong class="hover-title">${e(data.title)}</strong><p>${e(data.summary)}</p>${url?`<a class="hover-url" href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(url)} ↗</a>`:'<span class="hover-unknown">Original URL unavailable.</span>'}<div class="hover-meta">${data.aiSummary?'<span>AI summary</span>':''}<span>${e(data.state)}</span><time>Observed ${data.date==='?'?'unknown':e(data.date)}</time></div>`;card.hidden=false;placeHover();}
function queueHover(anchor,immediate=false){clearTimeout(hoverTimer);clearTimeout(hoverCloseTimer);if(anchor===hoverAnchor&&!$('#hover-card').hidden)return;hoverTimer=setTimeout(()=>showHover(anchor),immediate?0:160);}
function queueHoverClose(){clearTimeout(hoverTimer);clearTimeout(hoverCloseTimer);hoverCloseTimer=setTimeout(()=>{if(!$('#hover-card').matches(':hover')&&!$('#hover-card').contains(document.activeElement))hideHover();},260);}
document.addEventListener('pointerover',ev=>{if(ev.pointerType==='touch')return;const anchor=ev.target.closest(hoverSelector);if(anchor){anchor.removeAttribute('title');queueHover(anchor);}});
document.addEventListener('pointerout',ev=>{const anchor=ev.target.closest(hoverSelector);if(anchor&&!anchor.contains(ev.relatedTarget)&&!$('#hover-card').contains(ev.relatedTarget))queueHoverClose();});
document.addEventListener('focusin',ev=>{const anchor=ev.target.closest(hoverSelector);if(anchor){anchor.removeAttribute('title');queueHover(anchor,true);}});
document.addEventListener('focusout',ev=>{if(!$('#hover-card').contains(ev.relatedTarget)&&!ev.target.closest(hoverSelector)?.contains(ev.relatedTarget))queueHoverClose();});
$('#hover-card').addEventListener('pointerenter',()=>{clearTimeout(hoverCloseTimer);clearTimeout(hoverTimer);});
$('#hover-card').addEventListener('pointerleave',queueHoverClose);
document.addEventListener('keydown',ev=>{if(ev.key==='Escape')hideHover();});
document.addEventListener('click',ev=>{if(!$('#hover-card').contains(ev.target)){const anchor=ev.target.closest(hoverSelector);if(anchor&&ev.pointerType==='touch')showHover(anchor);else hideHover();}});
addEventListener('resize',placeHover);document.addEventListener('scroll',()=>hideHover(),true);

$('#analyze-form').addEventListener('submit',async ev=>{ev.preventDefault();const generation=authGeneration;const b=$('#analyze-button');b.disabled=true;$('#graph-loading').hidden=false;$('#analyze-form').classList.remove('invalid');status('');try{const result=await api('/api/agent/runs',{method:'POST',body:JSON.stringify({url:$('#input-url').value.trim()})});if(!authenticated||generation!==authGeneration)return;acceptWorkspace(result.graph,{reset:true});activeRunId=result.run.id;researchRuns=result.graph.researchRuns??[...researchRuns.filter(r=>r.id!==result.run.id),result.run];render();status('Ready. Copy the AI task to begin.',true);}catch(err){if(authenticated&&generation===authGeneration){$('#analyze-form').classList.add('invalid');status(err.message);}}finally{if(generation===authGeneration){b.disabled=false;$('#graph-loading').hidden=true;}}});
$('#connections-button').addEventListener('click',connections);$('#empty-connect-button').addEventListener('click',()=>currentRun()&&['ready','searching'].includes(currentRun().status)?copyTask():connections());$('#copy-task-button').addEventListener('click',copyTask);$('#history-button').addEventListener('click',history);
$('#stop-run-button').addEventListener('click',async()=>{const generation=authGeneration;const run=currentRun();if(!run)return;try{const result=await api(`/api/agent/runs/${encodeURIComponent(run.id)}/cancel`,{method:'POST',body:JSON.stringify({note:'Stopped from the local app.'})});if(!authenticated||generation!==authGeneration)return;acceptWorkspace(result.graph);status('Research cancelled.',true);}catch(err){if(authenticated&&generation===authGeneration)status(err.message);}});
function confirmQuit(){openInspector('<h2>Quit local app?</h2><p>This stops the local server. Your saved workspace stays on disk.</p><div class="dialog-actions"><button class="text-button" data-close>Keep open</button><button class="text-button stop-button" data-shutdown>Quit app</button></div>');}
$('#quit-button').addEventListener('click',confirmQuit);$('#login-quit-button').addEventListener('click',confirmQuit);
$('#refresh-button').addEventListener('click',()=>refresh());$('#rank-button').addEventListener('click',ranks);$('#mentions-button').addEventListener('click',mentions);$('#coverage-button').addEventListener('click',coverage);$('#inference-button').addEventListener('click',ev=>{showInferred=!showInferred;ev.currentTarget.setAttribute('aria-pressed',String(showInferred));drawGraph();});$('#import-button').addEventListener('click',()=>$('#import-dialog').showModal());
document.addEventListener('click',async ev=>{const b=ev.target.closest('[data-node],[data-inspect],[data-focus],[data-strategy],[data-prepare],[data-close],[data-content],[data-platform],[data-connect],[data-copy],[data-shutdown]');if(!b)return;if(b.hasAttribute('data-shutdown')){try{await api('/api/shutdown',{method:'POST',body:'{}'});closed=true;$('#inspector').close();if(authenticated)status('Local app stopped. You may close this tab.',true);else $('#login-status').textContent='Local app stopped. You may close this tab.';}catch(err){if(authenticated)status(err.message);else $('#login-status').textContent=err.message;}return;}if(b.dataset.copy){await copyText(b.dataset.copy);return;}if(b.dataset.connect){connections();return;}if(b.dataset.content){selectedContent=b.dataset.content;focus=null;selected=null;render();return;}if(b.dataset.platform){contentPlatform=b.dataset.platform;selectedContent=null;focus=null;render();return;}if(b.hasAttribute('data-close')){b.closest('dialog').close();return;}if(b.dataset.node||b.dataset.inspect){if($('#inspector').open)$('#inspector').close();inspectNode(b.dataset.node??b.dataset.inspect);}if(b.dataset.strategy)inspectStrategy(b.dataset.strategy);if(b.dataset.focus){focus=b.dataset.focus.startsWith('channel-')?null:b.dataset.focus;active=true;selected=focus;if($('#inspector').open)$('#inspector').close();render();}if(b.dataset.prepare){$('#input-url').value=b.dataset.prepare;$('#inspector').close();$('#input-url').focus();}});
$('#source-graph').addEventListener('keydown',ev=>{if((ev.key==='Enter'||ev.key===' ')&&ev.target.dataset.node){ev.preventDefault();inspectNode(ev.target.dataset.node);}});
for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',ev=>{if(ev.target===dialog)dialog.close();});
$('#import-form').addEventListener('submit',async ev=>{ev.preventDefault();const generation=authGeneration;try{let data;try{data=JSON.parse($('#import-json').value);}catch{throw new Error('Invalid JSON syntax.');}const result=await api('/api/import',{method:'POST',body:JSON.stringify(data)});if(!authenticated||generation!==authGeneration)return;acceptWorkspace(result.graph);$('#import-status').textContent=`+${result.report.added} added · ${result.report.duplicates} duplicates · reported metadata`;}catch(err){if(authenticated&&generation===authGeneration)$('#import-status').textContent=err.message;}});
function showLogin(session={}){
  const wasAuthenticated=authenticated;authenticated=false;authUserId=null;authGeneration++;graph=null;active=false;focus=null;selected=null;selectedContent=null;researchRuns=[];activeRunId=null;lastSnapshot='';guide=null;contentPlatform='all';hideHover();
  $('#authenticated-app').hidden=true;$('#login-gate').hidden=false;$('#account-name').textContent='';$('#input-url').value='';
  for(const id of ['source-graph','strategy-logos','content-carousel','topic-chips','scope-counters'])$('#'+id).replaceChildren();
  if(wasAuthenticated){for(const dialog of document.querySelectorAll('dialog'))if(dialog.open)dialog.close();$('#inspector-body').replaceChildren();}
  $('#import-json').value='';$('#import-status').textContent='';$('#analyze-button').disabled=false;$('#graph-loading').hidden=true;$('#analyze-form').classList.remove('invalid');
  $('#login-status').textContent=closed?'Local app stopped. You may close this tab.':session.error?String(session.error).slice(0,180):session.status==='pending'?'Waiting for Agentlas sign-in…':session.status==='error'?'Sign-in could not be completed. Try again.':'';
}
async function checkAuth(){
  if(authChecking||closed)return;authChecking=true;
  try{const session=await api('/api/auth/status');if(session.authenticated===true&&session.user?.id){if(authUserId&&authUserId!==session.user.id)showLogin();const first=!authenticated;authenticated=true;authUserId=session.user.id;$('#login-gate').hidden=true;$('#authenticated-app').hidden=false;$('#account-name').textContent=session.user.displayName||'Agentlas account';if(first)await refresh({quiet:true});}else if(authenticated||!$('#login-gate').hidden)showLogin(session);}
  catch(err){if(err.message!==STALE_RESPONSE)showLogin({status:'error',error:err.message});}finally{authChecking=false;}
}
$('#logout-button').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST',body:'{}'});showLogin({status:'signed-out'});}catch(err){status(err.message);}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkAuth().then(()=>refresh({quiet:true}));});
setInterval(()=>{if(!document.hidden)checkAuth().then(()=>refresh({quiet:true}));},2000);
checkAuth();
